spring.application.name=datashipper
spring.config.import[0]=optional:configserver:http://localhost:8888
spring.config.import[1]=optional:consul:localhost:8500
spring.config.import[2]=optional:nacos:http://localhost:8848/nacos